[versions]
kotlin = "2.0.21"
wgpu = "v0.0.0.10"
download = "5.6.0"
jreleaser = "1.13.1"
agp = "8.5.2"
jna = "5.15.0"
kotest = "6.0.0.M1"

[libraries]
download = { module = "de.undercouch.download:de.undercouch.download.gradle.plugin", version.ref = "download" }
kotlin-multiplatform = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jreleaser-plugin = { module = "org.jreleaser:org.jreleaser.gradle.plugin", version.ref = "jreleaser" }
commons-io = { module = "commons-io:commons-io", version = "2.16.1" }
gson = { module = "com.google.code.gson:gson", version = "2.11.0" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "4.12.0" }
zip4j = { module = "net.lingala.zip4j:zip4j", version = "2.11.5" }
android-library = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "agp" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

# Tests
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotest-core = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[plugins]
kotest = { id = "io.kotest.multiplatform", version.ref = "kotest" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[bundles]
kotest = ["kotest-core", "kotest-assertions"]