package webgpu

actual class WGPUAdapter(val value: Long)
actual class WGPUBindGroup(val value: Long)
actual class WGPUBindGroupLayout(val value: Long)
actual class WGPUBuffer(val value: Long)
actual class WGPUCommandBuffer(val value: Long)
actual class WGPUCommandEncoder(val value: Long)
actual class WGPUComputePassEncoder(val value: Long)
actual class WGPUComputePipeline(val value: Long)
actual class WGPUDevice(val value: Long)
actual class WGPUInstance(val value: Long)
actual class WGPUPipelineLayout(val value: Long)
actual class WGPUQuerySet(val value: Long)
actual class WGPUQueue(val value: Long)
actual class WGPURenderBundle(val value: Long)
actual class WGPURenderBundleEncoder(val value: Long)
actual class WGPURenderPassEncoder(val value: Long)
actual class WGPURenderPipeline(val value: Long)
actual class WGPUSampler(val value: Long)
actual class WGPUShaderModule(val value: Long)
actual class WGPUSurface(val value: Long)
actual class WGPUTexture(val value: Long)
actual class WGPUTextureView(val value: Long)
